# Este valor se usa para generar la navegación interna del sitio
url: https://agendacocrearte.com.ar

# Información de la aplicación
title: Espacio Cocrearte
version: "0.4.1"
description: "Sistema de gestión de pacientes para psicología infantil"
