# Este valor se usa para generar la navegaci贸n interna del sitio
url: https://agendacocrearte.com.ar

# Informaci贸n de la aplicaci贸n
title: Espacio Cocrearte
version: 0.4.7
description: Sistema de gesti贸n para profesionales de la salud mental
